name: 'Kestra Deploy Action'
description: 'Create, update or delete a list of resources from a folder recursively'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  namespace:
    description: 'Namespace to update'
    required: true
  directory:
    description: 'Folder containing your resources'
    default: './'
  override:
    description: 'to override flows if they already exist or not'
    default: 'false'
  delete:
    description: 'If resource not found in directory should be deleted from the namespace'
    required: false
    type: boolean
    default: false
  server:
    description: 'URL of your Kestra server'
    required: true
  apiToken:
    description: 'API Token (EE only)'
    required: false
  tenant:
    description: 'Tenant identifier (EE only, when multi-tenancy is enabled)'
    default: "main"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install CLI
      shell: bash
      # obviously this is overkill here, but later it will located be elsewhere
      run: |
        curl -L -o kestra-cli https://github.com/kestra-io/deploy-action/raw/refs/heads/v2-with-cli/kestra-cli
        chmod +x kestra-cli

    - name: Run CLI
      shell: bash
      run: |
        OPTS=""
        if [ "${{inputs.override}}" = "true" ]; then
          OPTS="--override"
        fi
        ./kestra-cli flows deploy ${{inputs.directory}}/my-log-flow.yml --host ${{inputs.server}} --token ${{inputs.apiToken}} --tenant ${{inputs.tenant}} $OPTS
