name: 'Kestra Deploy Action'
description: 'Create, update or delete a list of resources from a folder recursively'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  namespace:
    description: 'Namespace to update'
    required: true
  directory:
    description: 'Folder containing your resources'
    default: './'
  to:
    description: '(Namespace Files specific) Remote path to upload namespace files to'
    required: false
    default: /
  resource:
    description: 'Resource you want to update in your namespace, can be "flow" or "template"'
    required: true
    type: choice
    options:
      - flow
      - template
      - namespace_files
  server:
    description: 'URL of your Kestra server'
    required: true
  user:
    description: 'User for the basic auth'
    required: false
  password:
    description: 'Password for the basic auth'
    required: false
  delete:
    description: 'If resource not found in directory should be deleted from the namespace'
    required: false
    type: boolean
    default: false
  tenant:
    description: 'Tenant identifier (EE only, when multi-tenancy is enabled)'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.namespace }}
    - ${{ inputs.directory }}
    - ${{ inputs.to }}
    - ${{ inputs.resource }}
    - ${{ inputs.server }}
    - ${{ inputs.user }}
    - ${{ inputs.password }}
    - ${{ inputs.delete }}
    - ${{ inputs.tenant }}
